services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: always
    working_dir: .
    volumes:
      - ${DATA_DIRECTORY}:/data
    ports:
      - "${SPIND_SERVER_PORT}:8080"