services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: always
    volumes:
      - ${DATA_DIRECTORY}:/data
    ports:
      - "${SPIND_SERVER_PORT}:8080"
  web-client:
    build:
      context: .
      dockerfile: composeApp/Dockerfile
    restart: always
    ports:
      - "${SPIND_WEB_CLIENT_PORT}:80"